### ISSUE TITLE
Create classes diagram

### ISSUE THREAD

**Issue by pedroluiznogueira** [Java-Dojo-Server/recipes#4]
Estimate classes diagram:

- entities needed in the application
- relationship between entities

**Comment by pedroluiznogueira** [comment]
First idea:

![image](https://user-images.githubusercontent.com/81788112/162885939-2b0d79e8-eb96-4cc2-acb5-67ba8e5594ab.png)

@gabizinha12 @brMonteiro-G

**Comment by gabrielle-lima** [comment]
Um adendo só, sabendo que esse relacionamento vai ser de 1 pra muitos, seria melhor usarmos listas né?

**Comment by pedroluiznogueira** [comment]
simm, eu quis colocar esse diagrama só pra gente começar uma discussão, mas nem pensei em nada específico...

**Comment by pedroluiznogueira** [comment]
design feito:

![image](https://user-images.githubusercontent.com/81788112/163518979-c96a48c5-469f-428c-8b62-e675d24853e9.png)
